spring.application.name=restaurant-management-system

# Server
server.port=${PORT:8080}

# PostgreSQL Database
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d7toele7r5hc73dnrvn0-a.oregon-postgres.render.com:5432/restaurant_db_ijo0}
spring.datasource.username=${DB_USERNAME:nilesh}
spring.datasource.password=${DB_PASSWORD:DKLUyZUkMqrjStu6uZtT0DEoo7u0d7eO}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET:my-super-secret-key-for-restaurant-management-system-123456789}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Admin Email
app.admin.email=${ADMIN_EMAIL:}

# Mail Config
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:amancse40@gmail.com}
spring.mail.password=${MAIL_PASSWORD:irrdgrrgagnllupc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS Frontend URL
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:djziqxt8h}
cloudinary.api-key=${CLOUDINARY_API_KEY:113724743862921}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:_aL_gr8ZNcmAFUBryp47lyvgTAM}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
